<h2>Kontaktní formulář</h2>

<p>Kontaktujte nás odesláním formuláře níže.</p>

<form method="post" id="form-email">
	Vaše emailová adresa<br />
	<input type="email" name="email" required="required" value="<?php if (isset($_POST['email'])) echo(htmlspecialchars($_POST['email'])); ?>" /><br />
	<textarea name="zprava"><?php if (isset($_POST['zprava'])) echo(htmlspecialchars($_POST['zprava'])); ?></textarea><br />
	<input type="submit" value="Odeslat" />
</form>