<!DOCTYPE html>


<html lang="cs-cz">
	<head>
		<base href="/localhost" />
		<meta charset="UTF-8" />
		<title><?= $titulek ?></title>
		<meta name="description" content="<?= $popis ?>" />
		<meta name="keywords" content="<?= $klicova_slova ?>" />
		<link rel="stylesheet" href="style.css" type="text/css"/>
	</head>






<body>

<header>
	<h1>MVC - ukázkový web</h1>
</header>
		
<section class="toplista">
    <input id="menuprepinac" type="checkbox" />
    <label class='menuhamburger' for="menuprepinac">
    <div class='menutlacitko'></div>
  </label>
       <ul class="menu">
				<li><a href="clanek/uvod">Úvod statický</a></li>
				<li><a href="clanek/uvod1">Úvod s DATY</a></li>
				<li><a href="clanekdb">Články DB</a></li>
				<li><a href="kontakt">Kontakt</a></li>			
    </ul>
  </section>

<br clear="both" />
    <section id="">
	<article>
			<?php $this->kontroler->vypisPohled(); // vložení aktuálního pohledu do šablony ?>
	</article>
    </section>
		<footer>
			<p>Ukázkový WEB pro jednoduché MVC  
			<a href="http://www.ITnetwork.cz" target="_blank">ITnetwork.cz</a>.</p>
		</footer>
<body>
 
</html>



