<!DOCTYPE html>
<html lang="cs-cz">
	<head>
		<base href="/localhost" />
		<meta charset="UTF-8" />
		<title><?= $titulek ?></title>
		<meta name="description" content="<?= $popis ?>" />
		<meta name="keywords" content="<?= $klicova_slova ?>" />
		<link rel="stylesheet" href="style.css" type="text/css"/>

		<script src="script.js" defer></script>
	</head>




<body>
<header>
	<h1>MVC - ukázkový web</h1>
</header>
			
  <div class="content">
    <nav class="navigation">
      <a href="" class="menu">
        <span class="bar"></span>
        <span class="bar"></span>
        <span class="bar"></span>
        <span class="bar"></span>
      </a>

      <div class="nav-links">
			<ul>
				<li><a href="clanek/uvod">Úvod statický</a></li>
				<li><a href="clanek/uvod1">Úvod s DATY</a></li>
				<li><a href="clanekdb">Články DB</a></li>
				<li><a href="kontakt">Kontakt</a></li>			
			</ul>
      </div>
    </nav>
   <br clear="both" />
    <section id="">
			<?php $this->kontroler->vypisPohled(); // vložení aktuálního pohledu do šablony ?>
    </section>
		<footer>
			<p>Ukázkový WEB pro jednoduché MVC  
			<a href="http://www.ITnetwork.cz" target="_blank">ITnetwork.cz</a>.</p>
		</footer>

  </div>
</body>



</html>